baseURL: http://www.robbievanaert.com/
languageCode: en-us
defaultContentLanguage: en
title: Robbie C.M. van Aert
theme: "cupper-hugo-theme"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Assistant professor at Tilburg University
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  navTitleText: Robbie C.M. van Aert
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    # - name: Blog
    #   url: /post/
    #   weight: 2
    - name: Publications
      url: /publications/
      weight: 2
    - name: Software
      url: /software/
      weight: 3
    - name: Presentations
      url: /presentations/
      weight: 4
    - name: Curriculum Vitae
      url: /cv/cv_vanaert.pdf
      weight: 5
    - name: Side Projects
      url: /side/
      weight: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
