---
date: "2014-04-09"
title: "Presentations"
---

```{r create_list, echo = FALSE}
###############################################################################
##### CODE TO FORMAT BIBTEX ENTRIES TO RMARKDOWN TO CREATE A BIBLIOGRAPHY #####
###############################################################################

### HOW TO USE THE CODES:
# 1. CREATE A BIBTEX FILE USING, FOR INSTANCE, MENDELEY
# 2. YEAR SHOULD NOT BE SPECIFIED IN CASE OF IN PRESS PAPERS
# 3. IF AVAILABLE, THREE URLS NEED TO BE PROVIDED. THE ORDER OF THESE URLS ARE
#     (1) LINK TO WEBSITE OF JOURNAL, (2) LINK TO PDF OF PAPER, AND (3) LINK 
#     TO OSF. IF THESE URLS ARE NOT AVAILBLE, THEY DO NOT NEED TO BE PROVIDED. 
#     HOWEVER, THE ORDER IS IMPORTANT, SO NAs NEED TO BE ADDED IF, FOR EXAMPLE,
#     A LINK TO THE WEBSITE OF THE JOURNAL IS NOT AVAILABLE, BUT OSF IS AVAILABLE.

################################################################################

#################
### FUNCTIONS ###
#################

### Function for checking whether a RMarkdown link is NA
na_link <- function(x)
{
  substr(x, start = nchar(x)-1, stop = nchar(x)) == "()"
}

################################################################################

### Load overview file
df <- read.csv2("presentations_files/overview_presentations.csv")
# df <- read.csv2("static/presentations_files/overview_presentations.csv")

entries <- matrix(NA, nrow = nrow(df), ncol = 2, dimnames = list(1:nrow(df), 
                                                                 c("year", "entry")))

for (i in 1:nrow(df))
{
  
  dat <- df[i, ]
  
  entries[i,"year"] <- dat$year
  
  #############
  ### TITLE ###
  #############
  
  title <- dat$ï..title
  
  #############
  ### EVENT ###
  #############
  
  event <- dat$event
  
  ################
  ### LOCATION ###
  ################
  
  location <- dat$location
  
  ######################
  ### LINK TO SLIDES ###
  ######################
  
  slides <- paste0("[Slides](", dat$slides, ")")
  
  #####################
  ### LINK TO VIDEO ###
  #####################
  
  video <- paste0("[Video](", dat$video, ")")
  
  ################################################################################
  
  if (na_link(slides) & na_link(video))
  {
    entries[i,"entry"] <- paste0("* ", title, ". *", event, "*. ", location, ". ")  
  } else if (na_link(video))
  {
    entries[i,"entry"] <- paste0("* ", title, ". *", event, "*. ", location, ". ", 
                                 slides)  
  } else
  {
    entries[i,"entry"] <- paste0("* ", title, ". *", event, "*. ", location, ". ", 
                                 slides, " ", video)  
  }
  
}
```

### 2021

```{r 2021, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2021")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2020

```{r 2020, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2020")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2019

```{r 2019, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2019")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2018

```{r 2018, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2018")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2017

```{r 2017, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2017")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2016

```{r 2016, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2016")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2015

```{r 2015, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2015")

cat(as.vector(tmp[ ,2]), sep = "\n")
```

### 2014

```{r 2014, results = "asis", echo = FALSE}
tmp <- subset(entries, entries[ ,"year"] == "2014")

cat(as.vector(tmp[ ,2]), sep = "\n")
```